import { StyleSheet } from 'react-native';
import { Platform } from 'react-native';
export default StyleSheet.create({
  main: {
    backgroundColor: '#000',
    paddingHorizontal: 5,
    minHeight: '100%',
  },
  logo: {
    width: 135,
    height: 117,
    padding: 20,
  },
  logosection: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    marginTop: 40,
  },
  input: {
    height: 40,
    marginVertical: 5,
    borderWidth: 1,
    padding: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.25);',
    color: '#fff',
    marginBottom: 0,
    flex: 1,
    borderRadius: 5,
    fontFamily: 'Montserrat-Medium',
  },
  Countryinput: {
    height: 40,
    marginVertical: 5,
    borderWidth: 1,
    padding: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.25);',
    color: '#fff',
    // marginBottom: 0,
    // flex: 1,
    borderRadius: 5,
    fontFamily: 'Montserrat-Medium',
    // flex: 0.05
  },
  label: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
  },
  label1: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
  },
  required: {
    color: '#eee',
  },
  signintext: {
    textAlign: 'center',
    fontSize: 18,
    color: '#fff',
    marginVertical: 15,
    fontFamily: 'Montserrat-Bold',
  },
  required: {
    color: '#E66100',
  },
  forgottext: {
    color: '#fff',
    flex: 1,
    textAlign: 'right',
    color: '#E66100',
    fontSize: 15,
    fontFamily: 'Montserrat-Medium',
  },
  submitbtn: {
    backgroundColor: '#E66100',
    paddingVertical: 10,
    marginTop: 20,
    borderRadius: 5,
    fontFamily: 'Montserrat-Bold',
  },
  dltAccbtn: {
    backgroundColor: '#fc0317',
    paddingVertical: 10,
    marginTop: 20,
    borderRadius: 5,
    fontFamily: 'Montserrat-Bold',
  },
  submitbtntext: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Montserrat-Bold',
  },
  loginwith: {
    color: '#fff',
    textAlign: 'center',
    marginVertical: 20,
    fontSize: 14,
    fontFamily: 'Montserrat-Medium',
  },
  socialsection: {
    // margin: 10,
    flex: 2,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  socialmain: {
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
    // flex: 1,
  },
  registersection: {
    backgroundColor: '#fff',
    flex: 1,
    // flexDirection: "row",
    marginVertical: 20,
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
  },
  regtext1: {
    fontSize: 15,
    fontFamily: 'Montserrat-Medium',
    color: '#000',
    textAlign: 'center',
  },
  regtext2: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Montserrat-Regular',
    color: '#000',
    textAlign: 'center',
  },
  regbtn: {
    backgroundColor: '#E66100',
    paddingVertical: 8,
    marginTop: 10,
    borderRadius: 5,
    marginLeft: 0,
    paddingHorizontal: 40,
  },
  regbtntext: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 18,
    width: 100,
    fontWeight: '700',
    fontFamily: 'Montserrat-Medium',
  },
  noaccountmain: {
    flex: 2,
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 0,
    marginBottom: 50,
  },
  noaccount: {
    color: '#fff',
    fontSize: 14,
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    marginLeft: 20,
    marginRight: 20,
  },
  signuptext: {
    color: '#E66100',
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Montserrat-Medium',
  },
  privacyTandCText: {
    color: '#E66100',
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'Montserrat-Medium',
    textDecorationLine: 'underline',
  },
  privacyTandCText1: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'Montserrat-Medium',
    padding: 2,
  },
  eyeicon: {
    position: 'absolute',
    right: 10,
    zIndex: 9999,
    top: 34,
  },
  eyeiconMoblie: {
    position: 'absolute',
    right: 10,
    zIndex: 9999,
    top: 50,
  },
  title: {
    fontSize: 20,
    fontFamily: 'Montserrat-Bold',
    marginBottom: 20,
    color: '#000',
  },
  catbutton: {
    marginRight: 10,
    marginBottom: 10,
    backgroundColor: '#fff',
    padding: 10,
    borderRadius: 10,
  },
  catbuttontext: {
    color: '#E66100',
    textAlign: 'center',
    fontFamily: 'Montserrat-Bold',
  },
  catbuttonmain: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    borderRadius: 50,
  },
  titlemain: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  seealltext: {
    color: '#E66100',
    fontFamily: 'Montserrat-Bold',
    marginTop: 3,
  },
  catbuttonorange: {
    marginRight: 10,
    marginBottom: 10,
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#E66100',
    paddingRight: 20,
  },
  catbuttontextorange: {
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'Montserrat-Bold',
  },
  crossicon: {
    position: 'absolute',
    right: 0,
    top: 0,
  },
  bottomsheetmain: {
    backgroundColor: '#fff',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
  },
  bottomsheetheader: {
    backgroundColor: '#eee',
    paddingHorizontal: 10,
    paddingTop: 15,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
  },
  orangetitle: {
    color: '#E66100',
  },
  selectmain: {
    flex: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  checkmainSignup: {
    backgroundColor: '#000',
    padding: 0,
    margin: 0,
    // marginVertical: 10,
  },
  checkmain: {
    backgroundColor: '#fff',
    padding: 0,
    margin: 0,
    // marginVertical: 10,
  },
  checksection: {
    marginHorizontal: 10,
  },
  checkbtnmain: {
    flexDirection: 'row',
    flex: 1,
    padding: 20,
    // marginBottom:20,
  },
  applybtn: {
    backgroundColor: '#E66100',
    paddingRight: 20,
    flex: 1,
    padding: 10,
  },
  applybtn1: {
    backgroundColor: '#E66100',
    paddingRight: 20,
    flex: 1,
    padding: 10,
  },
  applytext: {
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'Montserrat-Bold',
    fontSize: 18,
  },
  closebtn: {
    flex: 1,
    padding: 10,
  },
  closebtntext: {
    textAlign: 'center',
    fontFamily: 'Montserrat-Bold',
  },
  backorg: {
    position: 'relative',
    top: 3,
  },
  clearall: {
    marginTop: 10,
  },
  space20: {
    height: 20,
  },
  space10: {
    height: 10,
  },
  cardmain: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 10,
    flex: 2,
    flexDirection: 'row',
    marginBottom: 15,
    paddingBottom: 20,
  },
  cardimg: {
    width: 100,
    height: 100,
    borderRadius: 7,
  },
  cardinnerright: {
    marginLeft: 10,
    flex: 1,
    paddingTop: 20,
  },
  cardinnerleft: {
    paddingTop: 20,
  },
  cardtext1: {
    color: '#E66100',
    fontSize: 15,
    fontFamily: 'Montserrat-Medium',
    marginBottom: 0,
  },
  cardtext2: {
    color: '#000',
    fontSize: 18,
    fontFamily: 'Montserrat-Bold',
    marginBottom: 5,
    flexDirection: 'column',
  },
  cardtext3: {
    color: '#000',
    fontSize: 16,
    marginBottom: 5,
    fontFamily: 'Montserrat-Medium',
    lineHeight: 23,
  },
  pricemain: {
    flexDirection: 'row',
    fontFamily: 'Montserrat-Medium',
    alignItems: 'center',
    marginTop: 5,
  },
  cardtext4: {
    marginRight: 10,
    fontFamily: 'Montserrat-Medium',
    fontSize: 22,
    textDecorationLine: 'line-through',
    color: '#000',
    fontWeight: '600',
  },
  cardtextPrice: {
    marginTop: 10,
    color: '#000',
    fontSize: 15,
    fontFamily: 'Montserrat-Medium',
    marginBottom: 2,
  },
  scrollViewContent: {
    flexGrow: 1,
  },
  cardtext5: {
    marginRight: 10,
    fontFamily: 'Montserrat-Medium',
    fontSize: 22,
    color: '#059002',
    fontWeight: '600',
  },
  cardtext6: {
    marginRight: 10,
    fontFamily: 'Montserrat-Bold',
    fontSize: 12,
    color: '#fff',
    backgroundColor: '#A9CF4B',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
    overflow: 'hidden',
  },
  cardtext7: {
    marginRight: 10,
    fontFamily: 'Montserrat-Medium',
    fontSize: 15,
    color: '#E66100',
    backgroundColor: 'rgba(254, 90, 62, 0.25)',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  image: {
    flex: 1,
    justifyContent: 'flex-end',
    width: 80,
    height: 24,
  },
  text: {
    color: 'white',
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'right',
    marginBottom: 9,
    marginRight: 5,
  },
  badgecontainer: {
    width: '100%',
    alignItems: 'flex-end',
    flex: 1,
    position: 'absolute',
    right: -10,
    top: -10,
    fontFamily: 'Montserrat-Medium',
  },
  slidermain: {
    backgroundColor: '#fff',
    borderRadius: 11,
    textAlign: 'center',
    width: '80%',
    // flex: 1,
    //  marginHorizontal: "10%",
    paddingTop: 0,
    marginTop: 20,
    overflow: 'hidden',
  },
  cardmainpopular: {
    // backgroundColor:"#fff",
    padding: 15,
    borderRadius: 10,
    // flex: 1,
    flexDirection: 'column',
    marginBottom: 50,
    paddingBottom: 20,
  },
  cardimg1: {
    borderRadius: 7,

    marginBottom: 20,
    textAlign: 'center',
    alignContent: 'center',
    ...Platform.select({
      ios: {
        width: '100%',
        height: 300,
      },
      android: {
        width: '100%',
        height: 300,
      },
    }),
  },
  cardinnerright1: {
    marginLeft: 0,
  },
  space50: {
    height: 50,
  },
  populartitle: {
    marginBottom: -30,
  },
  loadmaintext: {
    textAlign: 'center',
    color: '#fff',
    paddingVertical: 10,
    fontSize: 16,
    paddingHorizontal: 20,
    backgroundColor: '#E66100',
    fontFamily: 'Montserrat-Bold',
    borderRadius: 10,
    position: 'relative',
    overflow: 'hidden',
  },
  loadmain: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    borderRadius: 20,
    position: 'relative',
  },
  popcard1: {
    marginTop: 15,
    zIndex: 999999,
  },
  backbtn: {
    color: '#E66100',
    fontFamily: 'Montserrat-Bold',
    fontSize: 20,
    lineHeight: 0,
  },
  banner: {
    width: '100%',
    borderRadius: 50,
    marginTop: 8,
    // minHeight: 100,
    alignContent: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    shadowColor: '#000',
    marginBottom: 10,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.3,
    shadowRadius: 1.41,
    elevation: 23,
    height: 75,
  },
  overlay: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    minHeight: 100,
    borderRadius: 10,
  },
  mainbanner: {
    marginHorizontal: 10,
    borderRadius: 50,
  },
  bannertext: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 23,
    color: '#fff',
    textAlign: 'center',
    paddingHorizontal: 20,
    textTransform: 'uppercase',
    borderRadius: 50,
    marginTop: 35,
    marginBottom: 35,
  },
  deatilbadgemain: {
    marginHorizontal: 10,
  },
  detailbanner: {
    width: '100%',
    borderRadius: 10,
    marginBottom: 0,
    height: 400,
  },
  detailbadgecontainer: {
    top: 8,
    right: 0,
  },
  deatiltitle: {
    color: '#e66100',
    fontFamily: 'Montserrat-Medium',
    fontSize: 15,
  },
  detailtitlemain: {
    color: '#000',
    marginTop: 12,
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
    flex: 1,
    lineHeight: 25,
  },
  detailsmain: {
    color: '#e66100',
    fontSize: 16,
    fontFamily: 'Montserrat-Bold',
    marginBottom: 0,
  },
  list: {
    flex: 1,
    paddingLeft: 5,
    color: '#000',
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
    lineHeight: 25,
  },
  list1: {
    color: '#000',
    fontSize: 50,
    fontFamily: 'Montserrat-Medium',
    lineHeight: 39,
  },
  tagmain: {
    flexDirection: 'row',
    marginVertical: 10,
  },
  taginner: {
    backgroundColor: 'rgba(230, 97, 0, 0.05)',
    borderWidth: 1,
    borderColor: '#E66100',
    borderRadius: 15,
    overflow: 'hidden',
    alignContent: 'flex-start',
    justifyContent: 'flex-start',
  },
  tagtext: {
    paddingVertical: 5,
    paddingHorizontal: 30,
    // lineHeight:20,
    position: 'relative',
    overflow: 'hidden',
    paddingRight: 10,
    fontFamily: 'Montserrat-Medium',
  },
  tagimg: {
    position: 'absolute',
    marginHorizontal: 20,
    top: 4,
    bottom: -20,
    left: -10,
  },
  outlinebutton: {
    marginRight: 10,
    marginBottom: 10,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E66100',
  },
  outlinebuttontext: {
    color: '#E66100',
    textAlign: 'center',
    fontFamily: 'Montserrat-Bold',
  },
  outlinebuttonmain: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    borderRadius: 50,
    marginVertical: 10,
  },
  outlinebtnicon: {
    marginHorizontal: 20,
    paddingHorizontal: 10,
  },
  deatilsbtnmain: {
    backgroundColor: '#fff',
    margin: 0,
    zIndex: 9999,
    overflow: 'visible',
    height: 80,
    position: 'absolute',
    bottom: -20,
    width: '100%',
    borderRadius: 10,
  },
  deatilsbtninner: {
    margin: 0,
    padding: 5,
  },
  deatilsbtninner1: {
    margin: 0,
    padding: 5,
    width: 200,
  },
  orgtext: {
    color: '#E66100',
  },
  dashinner: {
    alignContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  dashmain: {
    backgroundColor: '#fff',
    borderRadius: 10,
    marginHorizontal: 10,
    marginVertical: 10,
    paddingVertical: 15,
    flexDirection: 'row',
  },
  dash1: {
    marginBottom: 10,
  },
  dash2: {
    fontSize: 20,
    fontFamily: 'Montserrat-Bold',
    marginBottom: 10,
    textAlign: 'center',
    color: '#000',
  },
  dash3: {
    fontSize: 14,
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    color: '#000',
  },
  dashmain2: {
    marginHorizontal: 10,
    marginTop: 10,
  },
  dashdata1: {
    backgroundColor: '#fff',
    borderRadius: 10,
    marginVertical: 10,
  },
  dashdata2: {
    // flex:1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  dashdata3: {
    borderRadius: 100,
    width: 50,
    height: 50,
    margin: 10,
  },
  dashdata4: {
    flex: 1,
    margin: 10,
    color: '#000',
  },
  dashdata5: {
    flex: 1,
  },
  dashdata5: {
    fontSize: 16,
    fontFamily: 'Montserrat-Bold',
    marginBottom: 5,
    color: '#000',
  },
  dashdata6: {
    fontFamily: 'Montserrat-Medium',
    color: '#000',
  },
  dashdata7: {
    fontSize: 15,
    fontFamily: 'Montserrat-Bold',
    color: '#E66100',
    margin: 10,
  },
  selectedbtn: {
    backgroundColor: '#E66100',
    borderRadius: 10,
    borderColor: '#eee',
    borderWidth: 0,
    fontFamily: 'Montserrat-Bold',
    fontSize: 20,
  },
  btncontainer: {
    marginBottom: 20,
    backgroundColor: '#fff',
    borderColor: '#eee',
    borderWidth: 0,
    marginVertical: 20,
    fontSize: 20,
  },
  buttonContainerStyle: {
    backgroundColor: '#f5f5f5',
    borderColor: '#eee',
    borderWidth: 0,
    borderRightWidth: 0,
    fontSize: 20,
  },
  buttonStyle: {
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 0,
    fontFamily: 'Montserrat-Bold',
    fontSize: 20,
  },
  textStyle: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 16,
    color: '#000',
    fontWeight: '600',
  },
  marginhz15: {
    marginHorizontal: 15,
  },
  expires: {
    right: -25,
    top: -15,
  },
  expirebtn: {
    overflow: 'hidden',
    borderTopRightRadius: 30,
    borderRadius: 10,
  },
  redeemmain: {
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 40,
    marginHorizontal: 20,
    textAlign: 'center',
  },
  redeemtext1: {
    fontSize: 16,
    fontFamily: 'Montserrat-Bold',
    marginTop: 20,
    textAlign: 'center',
    color: '#000',
  },
  redeemtext2: {
    fontSize: 15,
    fontFamily: 'Montserrat-Medium',
    marginVertical: 10,
    textAlign: 'center',
    marginBottom: 20,
    color: '#000',
  },
  orgoutline: {
    borderWidth: 2,
    borderColor: '#E66100',
    borderRadius: 8,
    padding: 10,
    lineHeight: 20,
  },
  orgoutline1: {
    borderWidth: 1,
    borderColor: '#E66100',
    borderRadius: 8,
    padding: 10,
    lineHeight: 20,
  },
  marginright10: {
    marginRight: 10,
  },
  dashdata8: {
    fontSize: 14,
    fontFamily: 'Montserrat-Medium',
    color: '#000',
    margin: 10,
    textAlign: 'center',
  },
  dashdata9: {
    fontFamily: 'Montserrat-Medium',
    color: '#000',
    margin: 10,
    textAlign: 'center',
    backgroundColor: '#E66100',
  },
  chatmain: {
    backgroundColor: '#f5f5f5',
    marginBottom: 0,
    paddingBottom: 0,
  },
  chatinner: {
    borderBottomWidth: 1,
    borderBottomColor: '#c1c1c1',
    paddingBottom: 10,
    marginBottom: 10,
  },
  mainform: {
    backgroundColor: '#fff',
    paddingHorizontal: 30,
    marginVertical: 20,
    marginHorizontal: 20,
    paddingVertical: 20,
    borderRadius: 10,
  },
  orangetitletext: {
    textAlign: 'center',
    fontSize: 18,
    fontFamily: 'Montserrat-Medium',
    color: '#E66100',
  },
  blacktext: {
    color: '#000',
  },
  blacktext1: {
    color: '#000',
  },
  mainformnobg: {
    paddingHorizontal: 30,
    marginVertical: 20,
    marginHorizontal: 10,
    paddingVertical: 20,
    borderRadius: 10,
  },
  verfimain: {
    margin: 0,
    padding: 0,
    alignItems: 'center',
    alignContent: 'center',
  },
  mainbg: {
    marginHorizontal: 20,
    marginVertical: 20,
  },
  date: {
    paddingBottom: 10,
  },
  notimain: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 10,
    fontFamily: 'Montserrat-Medium',
    borderLeftWidth: 3,
    borderLeftColor: '#E66100',
    marginBottom: 20,
  },
  noti1: {
    paddingBottom: 10,
    fontSize: 20,
    fontFamily: 'Montserrat-Medium',
  },
  noti2: {
    paddingBottom: 10,
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
  },
  sellertextbold: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 15,
  },
  sellertext: {
    fontFamily: 'Montserrat-Medium',
    marginBottom: 10,
    fontSize: 15,
  },
  dropdown1: {
    borderRadius: 5,
    paddingHorizontal: 5,
    borderColor: '#000',
    borderWidth: 1,
    // marginVertical: 10,
    paddingVertical: 3,
  },
  placeholderStyle1: {
    fontSize: 16,
  },
  selectedTextStyle1: {
    fontSize: 16,
    marginLeft: 8,
  },
  textarea: {
    height: 100,
  },
  checkoutmain: {
    marginHorizontal: 20,
    marginVertical: 20,
  },
  checktext1: {
    fontSize: 16,
    fontFamily: 'Montserrat-Bold',
    marginBottom: 8,
    color: '#000',
  },
  checktext2: {
    fontSize: 15,
    fontFamily: 'Montserrat-Medium',
    marginBottom: 8,
    color: '#000',
  },
  orangetitlebold: {
    fontSize: 18,
    fontFamily: 'Montserrat-Bold',
    marginBottom: 8,
    color: '#E66100',
    marginTop: 20,
    marginBottom: 10,
  },
  innerradiocheckout: {
    marginLeft: 20,
  },
  headerhome: {
    // height: 110,
    // paddingTop:50,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    ...Platform.select({
      ios: {
        paddingTop: 50,
        height: 120,
      },
      android: {
        paddingTop: 10,
        height: 80,
      },
    }),
  },
  headerhomeadr: {
    height: 80,
    paddingTop: 10,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerhomeios: {
    height: 110,
    paddingTop: 50,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerright: {
    flexDirection: 'row',
    marginTop: 10,
  },

  notify: {
    marginRight: 25,
    marginTop: 6,
  },
  profile: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 23,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#ccc',
    width: 40,
    height: 40,
  },
  receive: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 17,
    marginBottom: 30,
    marginTop: 10,
  },
  radio: {
    backgroundColor: '#000',
    color: '#fff',
    opacity: 1,
  },
  space: {
    height: 20,
  },
  otp: {
    color: '#fff',
    fontFamily: 'Montserrat-Medium',
  },
  otpmain: {
    marginBottom: 40,
    fontFamily: 'Montserrat-Medium',
  },
  Errlabel_font_size: {
    fontSize: 14,
    paddingLeft: 3,
    color: '#db2316',
    marginTop: 0,
  },
  loadingcontainer: {
    flex: 1,
    justifyContent: 'center',
    height: 100,
  },
  successRes: {
    color: 'red',
    textAlign: 'center',
  },
  verifyCode: {
    color: '#000',
  },
  backbtnmain: {
    flexDirection: 'row',
  },
  backbtntext: {
    color: '#E66100',
    fontSize: 18,
    fontWeight: '500',
  },
  headerhomesingle: {
    // height: 110,
    // paddingTop:50,
    paddingHorizontal: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginRight: 30,
    ...Platform.select({
      ios: {
        paddingTop: 50,
        // height: 100,
      },
      android: {
        paddingTop: 15,
        // height: 40,
      },
    }),
  },

  headerhomesingleblack: {
    // height: 110,
    // paddingTop:50,
    paddingHorizontal: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#000',
    ...Platform.select({
      ios: {
        paddingTop: 50,
        // height: 100,
      },
      android: {
        paddingTop: 15,
        // height: 40,
      },
    }),
  },
  formmain: {
    marginBottom: 15,
  },
  secext: {
    paddingLeft: 40,
    fontFamily: 'Montserrat-Medium',
  },
  serachmain: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  containerr: {
    backgroundColor: 'white',
    justifyContent: 'center',
    height: 50,
    marginLeft: 10,
  },
  containerr1: {
    backgroundColor: 'white',
    justifyContent: 'center',
    height: 50,
    marginLeft: 10,
  },
  dropdownn: {
    height: 60,
    borderColor: 'gray',
    borderWidth: 0.5,
    borderRadius: 8,
    marginTop: 0,
    textAlign: 'center',
    marginTop: 17,
    maxWidth: '200px',
    width: 200,
    marginLeft: 10,
  },
  placeholderStylee: {
    fontSize: 16,
  },
  iconStylee: {
    width: 0,
    height: 0,
    position: 'absolute',
    left: 100,
  },
  sortdrop: {
    alignItems: 'center',
  },
  sorttext: {
    fontFamily: 'Montserrat-Medium',
    paddingTop: 14,
    paddingHorizontal: 25,
    fontSize: 16,
  },
  toastifierConatiner: {
    margin: 10,
    marginRight: 10,
    marginBottom: 10,
    backgroundColor: '#fff',
    padding: 10,
    borderRadius: 10,
  },
  toastifierText: {
    textAlign: 'center',
    color: '#1cfc03',
  },
  paynowmain: {
    marginVertical: 20,
    alignContent: 'center',
    justifyContent: 'center',
    marginHorizontal: 0,
  },
  toast: {
    backgroundColor: '#fff',
    position: 'absolute',

    width: '100%',
    zIndex: 999999,
    overflow: 'visible',
    ...Platform.select({
      ios: {
        top: 40,
      },
      android: {
        top: 0,
      },
    }),
  },
  otp_war_text: {
    color: '#fff',
    // flex:1,
    // textAlign:"left",
    color: '#E66100',
    fontSize: 12,
    fontFamily: 'Montserrat-Medium',
  },
  checksection: {
    height: 300,
  },
  checksection1: {
    height: 120,
  },
  ProfileLogo: {
    width: 82,
    height: 82,
    borderRadius: 50,
    marginBottom: 10,
  },
  addupload: {
    borderRadius: 50,
    overflow: 'hidden',
  },
  profilelogosection: {
    // flex:1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    // marginTop:10
  },
  forgotBacktext: {
    color: '#fff',
    flex: 1,
    textAlign: 'center',
    color: '#E66100',
    fontSize: 15,
    fontFamily: 'Montserrat-Medium',
  },
  toolbar: {
    borderRadius: 20,
    marginHorizontal: 10,
    marginBottom: 10,
    borderTopWidth: 0,
  },
  checkOutBox: {
    padding: 0,
    margin: 0,
    marginVertical: 10,
    color: '#E66100',
    backgroundColor: '#f2f2f2',
  },
  wrapstyle: {
    // borderWidth:1
  },
  termtext: {
    color: '#E66100',
    fontSize: 15,
    fontFamily: 'Montserrat-Medium',
  },
  textcenter: {
    textAlign: 'center',
  },
  textcenter1: {
    textAlign: 'center',
  },
  thankyoutitle: {
    fontSize: 20,
    fontFamily: 'Montserrat-Bold',
    marginTop: 20,
    textAlign: 'center',
    color: '#000',
    marginHorizontal: 20,
    lineHeight: 30,
  },
  thankyoutitle1: {
    fontSize: 20,
    fontFamily: 'Montserrat-Bold',
    margin: 0,
    textAlign: 'center',
    color: '#000',
    marginHorizontal: 20,
    lineHeight: 30,
  },
  thankcontent: {
    paddingHorizontal: 30,
    marginHorizontal: 10,
    paddingVertical: 20,
    borderRadius: 10,
  },
  thankcontent1: {
    paddingHorizontal: 30,
    marginHorizontal: 10,
    paddingVertical: 20,
    borderRadius: 10,
  },
  thankbtnmain: {
    flexDirection: 'row',
    flex: 1,
    padding: 20,
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  thankbtnmain1: {
    flexDirection: 'row',
    flex: 1,
    padding: 20,
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  thankbtn1: {
    alignContent: 'center',
    alignItems: 'center',
    height: 60,
    paddingTop: 20,
    marginRight: 10,
    backgroundColor: '#f2f2f2',
    paddingRight: 20,
    flex: 1,
    padding: 10,
  },
  thankbtn2: {
    alignContent: 'center',
    alignItems: 'center',
    height: 60,
  },
  thankbtn21: {
    alignContent: 'center',
    alignItems: 'center',
    height: 50,
    width: 100,
  },
  dltbtn1: {
    alignContent: 'center',
    alignItems: 'center',
    // height:60,
    // paddingTop:20,
    // marginRight:10,
    backgroundColor: '#f2f2f2',
    paddingRight: 20,
    flex: 1,
    padding: 10,
    margin: 10,
  },
  dltbtn2: {
    alignContent: 'center',
    alignItems: 'center',
    // height:60
  },
  applytext1: {
    fontSize: 18,
    fontWeight: '800',
    color: '#E66100',
    fontFamily: 'Montserrat-Bold',
    textAlign: 'center'
  },
  thankimg: {
    width: 300,
    height: 300,
    marginLeft: 30,
  },
  applytext2: {
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'Montserrat-Bold',
    fontSize: 18,
    padding: 1,
    marginTop: 10,
  },
  bushours: {
    color: '#000',
    marginTop: 5,
    fontSize: 14,
    fontFamily: 'Montserrat-Medium',
    flex: 1,
    flexDirection: 'column',
    lineHeight: 20,
  },
  deatiltitlee: {
    color: '#e66100',
    fontFamily: 'Montserrat-Bold',
    fontSize: 17,
    marginTop: 20,
    marginBottom: -10,
  },
  detailtitlemainhours: {
    color: '#000',
    marginTop: 12,
    fontSize: 18,
    fontFamily: 'Montserrat-Medium',
    lineHeight: 25,
  },
  bannertextnew: {
    color: '#000',
    marginTop: 8,
    fontFamily: 'Montserrat-Bold',
    fontSize: 18,
    marginLeft: 10,
    marginBottom: 4,
  },
  marbottom40: {
    marginBottom: 40,
  },
  price1: {
    padding: 100,
  },
  cardtext22: {
    // color: '#000',
    // fontSize: 18,
    // fontFamily: 'Montserrat-Bold',
    // marginBottom: 5,
    // flexDirection:"column",
    width: '100%',
  },
  badgecontainer1: {
    right: '0%',
  },
  oopsContainer: {
    marginTop: 200,
    alignItems: 'center',
    justifyContent: 'center',
    alignContent: 'center',
    flexDirection: 'column',
    // height: 50
  },
  oopsmain: {
    justifyContent: 'center',
    alignItems: 'center',
    // marginVertical: 30,
    marginHorizontal: 20,
    textAlign: 'center',
  },
  oopsmainpagemain: {
    margin: 0,
    padding: 0,
    alignItems: 'center',
    alignContent: 'center',
  },
  oopsimg: {
    width: 400,
    height: 299,
    // marginRight: 30
  },
  chatHeader: {
    marginRight: 180,
    flexDirection: 'column',
    marginLeft: 10,
  },
  headerhomesingle11: {
    // height: 110,
    // paddingTop:50,
    paddingHorizontal: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 0,
    ...Platform.select({
      ios: {
        paddingTop: 0,
        // height: 100,
      },
      android: {
        paddingTop: 0,
        // height: 40,
      },
    }),
  },
  headerhomesingle23: {
    // height: 110,
    // paddingTop:50,
    // paddingHorizontal: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginRight: 30,
    ...Platform.select({
      ios: {
        paddingTop: 50,
        // height: 100,
      },
      android: {
        paddingTop: 15,
        // height: 40,
      },
    }),
  },
  secext1: {
    // paddingLeft: 40,
    fontFamily: 'Montserrat-Medium',
    // marginLeft: 30,
  },
  dashdata34: {
    borderRadius: 100,
    width: 50,
    height: 50,
    // margin: 10
  },
  infoTextSpaceWhite: {
    fontSize: 13,
    fontStyle: 'italic',
    color: '#FFF',
  },
  infoTextSpace: {
    fontSize: 13,
    fontStyle: 'italic',
    color: '#000',
  },
  containerDate: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  containerDateCoupon: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 3,
  },
  contentContainerDate: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
  },
  textDate: {
    fontFamily: 'Montserrat-Medium',
    fontSize: 15,
    padding: 6,
    borderRadius: 10,
    color: '#e66100',
    backgroundColor: '#e661001a',
  },
  containerAbout: {
    display: 'flex',
    flexDirection: 'row',
  },
  listAbout: {
    color: '#000',
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
    lineHeight: 25,
    marginTop: 0,
  },
  listItemAbout: {
    color: '#000',
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
    lineHeight: 25,
    marginTop: 0,
  },
  linkAbout: {
    color: '#000',
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
    lineHeight: 25,
    marginTop: 0,
  },
  paragraphAbout: {
    color: '#000',
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
    width: '100%',
    lineHeight: 25,
    marginTop: 0,
  },
  separator: {
    height: 1,
    backgroundColor: 'gray',
    marginVertical: 10,
    width: '100%',
  },
  noaccountmainSeparator: {
    flex: 2,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 0,
    marginBottom: 10,
  },
  helpBtn: {
    color: '#e66100',
    backgroundColor: '#e661003d',
    borderRadius: 8,
    padding: 10,
    lineHeight: 20,
  },
  privacyPolicy: {
    fontSize: 14,
    fontStyle: 'italic',
    color: '#FFF',
    textDecorationLine: 'underline',
  },
  BtnContainer: { flexDirection: 'row', justifyContent: 'space-around' },
  BtnView1: {
    height: 50,
    backgroundColor: '#fff',
    margin: 10,
    borderRadius: 10,
    ...Platform.select({
      ios: {
        width: 200,
      },
      android: {
        width: 175,
      },
    }),
    borderColor: '#E66100',
    borderStyle: 'solid',
    borderWidth: 2,
    alignItems: 'center',
  },
  BtnView2: {
    height: 50,
    backgroundColor: '#E66100',
    margin: 10,
    borderRadius: 10,
    width: 175,
    borderColor: '#E66100',
    borderStyle: 'solid',
    borderWidth: 2,
    alignItems: 'center',
  },
  BtnText1: {
    color: '#E66100',
    fontFamily: 'Montserrat-Bold',
    textAlign: 'center',
    padding: 8,
    fontSize: 20,
    fontWeight: '800',
  },
  BtnText2: {
    color: '#fff',
    fontFamily: 'Montserrat-Bold',
    textAlign: 'center',
    padding: 8,
    fontSize: 20,
    fontWeight: '800',
  },
  marketPlaceContainer: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: 15,
    width: '92%',
    // height: 90,
    borderRadius: 10,
    marginBottom: 10,
    flex: 1,
    flexDirection: 'row',
  },
  marketPlaceContainerDefault: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: 15,
    width: '92%',
    // height: 90,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#E66100',
    marginBottom: 10,
    flex: 1,
    flexDirection: 'row',
  },
  cardimg2: {
    width: 70,
    height: 70,
    borderRadius: 7,
    margin: 8
  },
  noteicon: {
    transform: [{ rotate: '45deg' }],
    alignSelf: 'flex-end',
    // marginHorizontal: 20,
    padding: 10,
    marginVertical: 18
  },
  marketPlaceText: {
    color: '#000000',
    fontFamily: 'Montserrat-Medium',
    fontSize: 18,
    // textAlign: 'center',
    marginVertical: 15,
    padding: 10,
    width: 220,
    // height: 500,
    flexWrap: 'wrap'
  },
  bold: {
    fontWeight: '800'
  },
  marketplaceText2: {
    marginTop: 6, fontSize: 13,
    fontFamily: 'Montserrat-Medium',
    color: '#000',
  },
  marketplaceText1: {
    fontSize: 20,
    fontFamily: 'Montserrat-Medium',
    color: '#000',
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
    textDecorationColor: '#A9CF4B',
  }
});
